# Jekyll Resume Theme

# Site settings
title: Chip Oglesby | Resume
email: chip@creativesparkcolumbia.com
description: The online resume for Chip Oglesby.                    
baseurl: "http://chipoglesby.github.io/jekyll-resume"
url: "http://chipoglesby.github.io/jekyll-resume"
name: Chip Oglesby 
job: Data Scientist
location: Fort Collins, CO
languages: R, Bash, ggplot         
twitter_username: chipoglesby 
github_username:  chipoglesby 
email_address: chip@creativesparkcolumbia.com

# Build settings
markdown: kramdown
