# Jekyll Resume Theme

# Site settings
title: Chip Oglesby | Resume
email: chip@creativesparkcolumbia.com
description: The online resume for Chip Oglesby.                    
baseurl: "https://www.chipoglesby.com/resume"
url: ""
name: Chip Oglesby 
job: Data Scientist
location: Van Wyck, SC
languages: R, git & Bash         
twitter_username: chipoglesby 
github_username:  chipoglesby 
email_address: chip@creativesparkcolumbia.com

# Build settings
markdown: kramdown
